name: Business App CI/CD

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows]   # your Windows self-hosted runner

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t mydockerhubusername/business-app:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push mydockerhubusername/business-app:latest

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/business-app -n default

      # Optional: Verify deployment
      - name: Verify deployment
        run: |
          kubectl get pods -n default
          kubectl get svc -n default
