apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: business-app
  template:
    metadata:
      labels:
        app: business-app
    spec:
      containers:
      - name: business-app
        image: mydockerhubusername/business-app:latest
        ports:
        - containerPort: 3000
