apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-hostpath
  template:
    metadata:
      labels:
        app: busybox-hostpath
    spec:
      nodeName: k8s-worker2  # replace with your worker node
      containers:
        - name: busybox
          image: nginx:1.21.6   # lightweight, easy to load offline
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "sleep 3600"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          hostPath:
            path: /data/k8s/busybox
            type: DirectoryOrCreate

