apiVersion: v1
kind: Service
metadata:
  name: postgres # This name must match the serviceName in the StatefulSet
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None # This makes the service "headless"
  selector:
    app: postgres-stateful # This must match the labels on your pods