apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefull-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/nginx    # make sure this directory exists on your node
