apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: hello
spec:
  containers:
  - name: hello-container
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=Hello Kubernetes World!"
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: NodePort
