name: Deploy CRD to Kubernetes

on:
  push:
    paths:
      - 'manifests/myapp-crd.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Apply CRD
      run: |
        kubectl apply -f manifests/myapp-crd.yaml
