apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deploy
  labels:
    app: calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: rajuprudhvi/calculator-app:latest
        ports:
        - containerPort: 5000
