# flux-system/gitrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-gitops-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rajuKollati1/flux-demo
  ref:
    branch: main
  timeout: 60s
