apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
interval: 10m
path: ./clusters/my-cluster/flux-system
prune: true
sourceRef:
  kind: GitRepository
  name: flux-system
