[lab_vms]
vm1 ansible_host=192.168.1.10
vm2 ansible_host=192.168.1.20

[lab_vms:vars]
# Replace 'ubuntu' with your actual remote SSH username
ansible_user=raju
# If you are using a specific SSH key, point to it here:
#ansible_ssh_private_key_file=~/.ssh/id_rsa
# Optional: if using passwords, uncomment the line below (not recommended for security)
ansible_password=VMware1!
ansible_become_password=VMware1!