---
- name: Start Containerd Service
  hosts: lab_vms
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure containerd is started
      ansible.builtin.service:
        name: containerd
        state: started
