---
- name: Stop Containerd Service
  hosts: lab_vms
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure containerd is stopped
      ansible.builtin.service:
        name: containerd
        state: stopped
