apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-storage
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-pv-handle
    readOnly: false
    volumeAttributes:
      source: "//192.168.0.171/k8s-share"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default

