apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default   # Or change if needed
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: "25.9.0"  # Optional: lock version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
    pushgateway:
      enabled: true
    server:
      service:
        type: NodePort
