apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "25.8.*"   # pick a stable version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  values:
    alertmanager:
      persistentVolume:
        enabled: true
        storageClass: ""   # "" = use default StorageClass
        size: 2Gi
    server:
      persistentVolume:
        enabled: true
        storageClass: ""   # "" = use default StorageClass
        size: 5Gi
