apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 25.21.0  # example version
  interval: 1m
  values:
    alertmanager:
      persistentVolume:
        enabled: true
        storageClass: smb-storage
        size: 2Gi

    server:
      persistentVolume:
        enabled: true
        storageClass: smb-storage
        size: 8Gi

    pushgateway:
      persistentVolume:
        enabled: false  # or true if needed
