apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: 25.21.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
      persistentVolume:
        enabled: true
        storageClass: smb-storage
        size: 2Gi

    server:
      enabled: true
      persistentVolume:
        enabled: true
        storageClass: smb-storage
        size: 8Gi

    pushgateway:
      enabled: false
