name: Deploy Prometheus

on:
  workflow_dispatch:  # allows manual trigger only

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      - name: Helm Upgrade or Install Prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring --set service.type=LoadBalancer

