name: Deploy Prometheus with Helm

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # manually trigger from GitHub UI

jobs:
  deploy:
    runs-on: self-hosted  # your Windows self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add Prometheus Helm repo
      run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repos
      run: helm repo update

    - name: Install Prometheus with Helm
      run: |
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace monitoring
