# deploy-crd.yaml
name: Deploy CRD

on:
  push:
    paths:
      - 'manifests/**'
      - '.github/workflows/**'
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      - name: Apply CRD to cluster
        run: kubectl apply -f manifests/myapp-crd.yaml
