name: Deploy Prometheus via FluxCD

on:
  push:
    paths:
      - 'clusters/production/prometheus-helm*'
    branches:
      - main

jobs:
  deploy-prometheus:
    name: FluxCD Sync & Validate
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flux CLI
        run: |
          choco install flux -y
        shell: powershell

      - name: Confirm Flux version
        run: flux --version
        shell: powershell

      - name: Bootstrap cluster if needed
        run: |
          flux check --pre
        shell: powershell
        continue-on-error: true

      - name: Force Flux reconcile
        run: |
          flux reconcile source git flux-system --with-source
        shell: powershell

      - name: Confirm Prometheus release
        run: |
          flux get helmreleases -n monitoring
        shell: powershell
