name: Deploy SMB PVC to Kubernetes

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Apply StorageClass
      run: kubectl apply -f k8s-storage/smb-storageclass.yaml --validate=false

    - name: Apply Persistent Volume
      run: kubectl apply -f k8s-storage//smb-pv.yaml

    - name: Apply PVC
      run: kubectl apply -f k8s-storage//smb-pvc.yaml

    - name: Deploy Pod using PVC
      run: kubectl apply -f k8s-storage//pod-with-pvc.yaml
