name: Kubernetes Nodes Status

on:
  workflow_dispatch:

jobs:
  get-nodes:
    runs-on: self-hosted

    steps:
      - name: Print current user
        run: whoami

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=/home/k8s-m/.kube/config" >> $GITHUB_ENV

      - name: Show KUBECONFIG value
        run: echo "KUBECONFIG=$KUBECONFIG"

      - name: Run 'kubectl get nodes'
        run: |
          echo "Running kubectl get nodes..."
          kubectl get nodes -o wide
