name: Deploy Grafana on Windows Runner (Kubeconfig pre-configured)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Helm (if not installed)
      shell: powershell
      run: |
        if (-not (Get-Command helm -ErrorAction SilentlyContinue)) {
          Invoke-WebRequest -Uri https://get.helm.sh/helm-v3.14.0-windows-amd64.zip -OutFile helm.zip
          Expand-Archive -Path helm.zip -DestinationPath .
          Copy-Item .\windows-amd64\helm.exe -Destination "C:\Program Files\helm\helm.exe"
          $env:Path += ";C:\Program Files\helm"
        }

    - name: Add Helm repo and install Grafana
      shell: powershell
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        helm upgrade --install grafana grafana/grafana `
          --namespace monitoring `
          --create-namespace `
          --set adminPassword='admin123' `
          --set service.type=LoadBalancer

    - name: Verify Grafana Installation
      shell: powershell
      run: |
        kubectl get pods -n monitoring
