name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "✅ Hello from Raju's self-hosted runner!"
